### PR TITLE
Add plan forcing encrypted uploads.

### PR DESCRIPTION
**Pull request by jmcarp**
Pairing with @jseppi

[Resolves https://github.com/cloudfoundry-community/s3-broker/issues/14]

### CODE REVIEW

**Comment by cnelson** [comment]
I think this needs to be an option you can specify when using any other plan.  For example, just to check the compliance box, Federalist would like to have encryption on the public plan and I think it makes more sense to be able to do something like `cf create-service bucket s3 basic-public -c '{"require_encryption: "AES256"}'` or `'{"require_encryption: true}'` than it does to have a `-encrypted` version of every plan we offer.

WDYT?

**Comment by jmcarp** [comment]
Configuring encryption policy via provision parameters makes sense--but if we're going to configure one part of the bucket policy via parameters, why not do the whole policy that way, like `-c '{"require_encryption": "AES256", "public": true}'` ?

**Comment by cnelson** [comment]
Other than backwards compatibility? I'm sure we have apps that depend on the `basic-public` plan existing at this point but I agree that we should enable options for s3 buckets in a uniform way as encryption isn't going to be the last option this broker will have to expose -- I expect enabling logging and backups ( https://github.com/18F/cg-product/issues/588 ) will get prioritized soon as we've had multiple users ask for it. 

It makes sense to me that all options are enabled with parameters and not shoved into the plan name but maybe we should do a bit of user research and see what our users think is more intuitive between these options:

`cf create-service foo s3 basic-public-encrypyted-logging-backups`
or 
`cf create-service foo s3 basic -c '{"require_encryption": true, "public": true, "logging": true, "backups": true}'`

Do we need to worry about the dashboard?  Does it support passing parameters to services?

**Comment by jmcarp** [comment]
Looks like the dashboard doesn't yet pass parameters to services:

screen shot 2017-02-08 at 10 00 45 am

FWIW, I haven't noticed anybody asking about this in support.

**Comment by pburkholder** [comment]
Superseded by #17

**Pull request closed without merging**
